# Generated by Django 3.2 on 2021-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='new', max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
