# Generated by Django 3.2 on 2021-04-25 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('record_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DELETED', 'Delete'), ('ACTIVE_LOCKED', 'Active Locked')], default='ACTIVE', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, null=True)),
                ('last_login', models.DateField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=None, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_customuser_changed_by', related_query_name='accounts_customusers_changed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_customuser_created_by', related_query_name='accounts_customusers_created_by', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('first_name', 'last_name', 'username', 'email'),
                'permissions': (('custom_view_security_menu', 'View Security Menu'), ('custom_add_user', 'Add User'), ('custom_edit_user', 'Edit User'), ('custom_view_users', 'View Users'), ('custom_add_role', 'Add Role'), ('custom_edit_role', 'Edit Role'), ('custom_view_roles', 'View Roles')),
                'default_permissions': (),
            },
        ),
    ]
