# Generated by Django 3.2 on 2021-04-25 09:27
from django.contrib.auth.hashers import make_password
from django.db import migrations

from accounts.models import RecordStatus


def create_default_user(apps, schema_editor):
    user_account = apps.get_model('accounts', 'CustomUser')

    try:
        default_user = user_account()
        default_user.first_name = 'System'
        default_user.last_name = 'Administrator'
        default_user.phone_number = '256774669561'
        default_user.is_admin = True
        default_user.is_staff = True
        default_user.is_superuser = True
        default_user.is_active = True
        default_user.email = 'admin@example.com'
        default_user.username = 'administrator'
        default_user.password = make_password('password123')
        default_user.record_status = RecordStatus.ACTIVE.name
        default_user.save()
    except Exception as ex:
        print(f'Default user creation error : {ex}')
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_default_user)]
